### ISSUE TITLE
$ in type paramater of a variable

### ISSUE THREAD

**Issue by gaya3chandran1** [tmccombs/hcl2json#27] opened 2021-06-22 09:32 UTC
type        = map(string)
is getting converted to 
"type": "${map(string)}"
  Is there a way , it can convert to json without introducing $

**Comment by tmccombs** [comment] 2021-06-23 05:39
I believe this is a duplicate of #12. As mentioned in that issue, the problem here is that hcl2json needs to know the specific schema of the incoming hcl to know that `map(string)` shouldn't be treated as an expression.  I'm open to adding a way to provide a schema, but I'm not exactly sure what that would look like.

I'm going to close, but if you think this is somehow distinct from #12, feel free to reopen.

**Closed by tmccombs** 2021-06-23 05:39 UTC
