### ISSUE TITLE
depends_on attribute is converted incorrectly.

### ISSUE THREAD

**Issue by prakkarp** [tmccombs/hcl2json#31] opened 2021-08-18 05:50 UTC
hcl:
resource "aws_sns_topic" "test_topic" {
  name         = "test_topic"
  display_name = "Test Topic"
  depends_on = [
    aws_iam_role_policy.example,
  ]
}
With the above terraform init and plan works fine.

json generated by hcl2json:
        "aws_sns_topic": {
            "test_topic": [
                {
                    "depends_on": [
                        "${aws_iam_role_policy.example}"
                    ],
                    "display_name": "Test Topic",
                    "name": "test_topic"
                }
            ]
        }
When I try to do terraform init it gives the following error:
Error: Invalid expression

  on test.tf.json line 27, in resource.aws_sns_topic.test_topic[0].depends_on:
  56:                         "${aws_iam_role_policy.example}"

A single static variable reference is required: only attribute access and
indexing with constant keys. No calculations, function calls, template
expressions, etc are allowed here.

**Comment by tmccombs** [comment] 2021-08-18 18:53
This is a duplicate of #12

**Closed by tmccombs** 2021-08-18 18:53 UTC
